[package]
authors = ["Bhargav Annem <bhargav.annem@gmail.com>"]
description = "Rust implementation of KZG point evaluation"
edition = "2021"
license = "MIT"
name = "kzg-rs"
version = "0.1.0"
repository = "https://github.com/succinctlabs/kzg-rs"

[dependencies]
serde_derive = { version = "1.0", optional = true }
serde = { version = "^1.0", optional = true, default-features = false, features = [
    "alloc",
    "derive",
] }
glob = "0.3.1"
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
serde_yaml = { version = "0.9", optional = true }
once_cell = "1.19.0"
bls12_381 = { git = "https://github.com/sp1-patches/bls12_381/", branch = "patch-v0.8.0" }
sha2 = "0.10.8"
ff = { version = "0.13.0", features = ["derive"] }
include_bytes_aligned = "0.1.3"

[build-dependencies]
bls12_381 = { git = "https://github.com/sp1-patches/bls12_381/", branch = "patch-v0.8.0" }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_yaml", "dep:serde_derive"]
